[theme]
primaryColor="#013BA2ff"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#31AEE5ff;"
# textColor="#31333F"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[logger]
level = "debug"

[browser]
gatherUsageStats = false
